# Pytis translations
# Copyright (C) 2006-2017 OUI Technology Ltd.
# This file is distributed under the same license as the Pytis package.
# Tomas Cerha <cerha@brailcom.org>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: pytis 0.1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2022-09-07 11:50+0200\n"
"PO-Revision-Date: 2022-05-13 14:08+0200\n"
"Last-Translator: Hynek Hanke <hanke@brailcom.org>\n"
"Language-Team: Czech <wiking@lists.freebsoft.org>\n"
"Language: cs\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=((n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2);\n"

#: ../lib/pytis/data/access.py:432
msgid "Access denied"
msgstr "Neoprávněný přístup"

#: ../lib/pytis/data/dbapi.py:89
msgid "Waiting for server recovery"
msgstr "Čekám na zotavení serveru"

#: ../lib/pytis/data/dbapi.py:101
msgid "Can't connect to database"
msgstr "Nemohu se připojit do databáze"

#: ../lib/pytis/data/dbapi.py:231
msgid "Database interface error"
msgstr "Chyba v databázovém rozhraní"

#: ../lib/pytis/data/dbapi.py:250
msgid "Database connection timeout"
msgstr "Vypršel časový limit pro navázání databázového spojení"

#: ../lib/pytis/data/dbapi.py:252 ../lib/pytis/data/dbapi.py:387
msgid "Database connection error"
msgstr "Chyba databázového spojení"

#: ../lib/pytis/data/dbapi.py:266
msgid "Database operational error"
msgstr "Chyba databázové operace"

#: ../lib/pytis/data/dbapi.py:274
msgid "Database internal error"
msgstr "Interní databázová chyba"

#: ../lib/pytis/data/dbapi.py:278
msgid "Database integrity violation"
msgstr "Porušení integrity dat v databázi"

#: ../lib/pytis/data/dbdata.py:292
msgid "Too many database connections"
msgstr "Příliš mnoho databázových spojení"

#: ../lib/pytis/data/dbdata.py:722
msgid "Database error"
msgstr "Databázová chyba"

#: ../lib/pytis/data/dbdata.py:791
msgid "Invalid user name or password"
msgstr "Chybné uživatelské jméno nebo heslo"

#: ../lib/pytis/data/postgresql.py:426 ../lib/pytis/data/postgresql.py:536
#: ../lib/pytis/data/postgresql.py:548
msgid "Method not implemented"
msgstr "Volána neimplementovaná metoda"

#: ../lib/pytis/data/postgresql.py:3556
msgid "Invalid database counter value"
msgstr "Chybná hodnota čítače z databáze"

#: ../lib/pytis/data/types_.py:373
#, python-format
msgid "Wildcard matching not supported for values of type '%s'."
msgstr "Hvězdičkové výrazy nejsou podporovány pro hodnoty typu '%s'."

#. User input validation error message.
#: ../lib/pytis/data/types_.py:380
msgid "Empty value"
msgstr "Prázdná hodnota"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:396
msgid "Invalid value"
msgstr "Neplatná hodnota"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:544
#, python-format
msgid "Minimal value is %(minimum)s"
msgstr "Minimální hodnota je %(minimum)s"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:547
#, python-format
msgid "Maximal value is %(maximum)s"
msgstr "Maximální hodnota je %(maximum)s"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:587
#, python-format
msgid "Minimal size %(minlen)s not satisfied"
msgstr "Nedodržena minimální velikost %(minlen)s"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:589
#, python-format
msgid "Maximal size %(maxlen)s exceeded"
msgstr "Maximální velikost %(maxlen)s překročena"

#: ../lib/pytis/data/types_.py:740
msgid "Lower range bound higher than the upper one"
msgstr "Dolní hranice rozsahu je vyšší než horní"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:833
msgid "Not an integer"
msgstr "Není to celé číslo"

#: ../lib/pytis/data/types_.py:1005
msgid "Invalid number"
msgstr "Není to povolené číslo"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1138
#, python-format
msgid "Minimal length %(minlen)s characters not satisfied"
msgstr "Nedodržena minimální délka %(minlen)s znaků"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1140
#, python-format
msgid "Maximal length %(maxlen)s characters exceeded"
msgstr "Řetězec přesahuje maximální délku %(maxlen)s znaků"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1266
msgid "Please use mix of letters and non-letters in your password"
msgstr "Použijte ve svém hesle kombinaci písmenných a nepísmenných znaků"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1272
msgid "Enter the password twice to eliminate typos"
msgstr "Zadejte heslo dvakrát pro eliminování překlepů"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1275
msgid "Passwords don't match"
msgstr "Kontrolní zadání hesla neodpovídá"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1298
msgid "Invalid MD5 hash"
msgstr "Neplatná MD5 suma"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1305 ../lib/pytis/data/types_.py:1343
#: ../lib/pytis/data/types_.py:1373 ../lib/pytis/data/types_.py:1393
#: ../lib/pytis/data/types_.py:2113
msgid "Invalid format"
msgstr "Neplatný formát"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1328
msgid "Invalid color format ('#RGB' or '#RRGGBB')"
msgstr "Formát barvy neodpovídá ('#RGB' nebo '#RRGGBB')"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1348
#, python-format
msgid "Invalid inet address mask: %(mask)s"
msgstr "Neplatná maska inet adresy: %(mask)s"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1355
#, python-format
msgid "Invalid inet address value %(addr)s"
msgstr "Neplatná hodnota inet adresy: %(addr)s"

#: ../lib/pytis/data/types_.py:1520
msgid "Invalid date or time format"
msgstr "Chybný formát data nebo času"

#: ../lib/pytis/data/types_.py:1727
msgid "Date outside the allowed range"
msgstr "Datum mimo povolený rozsah"

#: ../lib/pytis/data/types_.py:2129
#, python-format
msgid "%d min"
msgid_plural "%d min"
msgstr[0] "%d min"
msgstr[1] "%d min"
msgstr[2] "%d min"

#: ../lib/pytis/data/types_.py:2131
#, python-format
msgid "%d h"
msgid_plural "%d h"
msgstr[0] "%d hod"
msgstr[1] "%d hod"
msgstr[2] "%d hod"

#: ../lib/pytis/data/types_.py:2133
#, python-format
msgid "%d day"
msgid_plural "%d days"
msgstr[0] "%d den"
msgstr[1] "%d dny"
msgstr[2] "%d dní"

#: ../lib/pytis/data/types_.py:2135
msgid "less than 1 min"
msgstr "méně než 1 min"

#: ../lib/pytis/data/types_.py:2246
msgid "Invalid boolean type input value"
msgstr "Neplatná vstupní hodnota typu boolean"

#: ../lib/pytis/data/types_.py:2473
msgid "Invalid graphics format"
msgstr "Neplatný grafický formát"

#: ../lib/pytis/data/types_.py:2531
#, python-format
msgid "Minimal pixel size %(minsize)s exceeded"
msgstr "Minimální rozměr %(minsize)s pixelů nedodržen"

#: ../lib/pytis/data/types_.py:2534
#, python-format
msgid "Maximal pixel size %(maxsize)s exceeded"
msgstr "Maximální rozměr %(maxsize)s pixelů překročen"

#: ../lib/pytis/data/types_.py:2538
#, python-format
msgid "Unsupported format %(format)s; valid formats: %(formats)s"
msgstr "Nepodporovaný formát %(format)s; platné formáty: %(formats)s"

#: ../lib/pytis/data/types_.py:2585
msgid "Invalid hierarchical value format"
msgstr "Chybný formát hierarchické hodnoty"

#: ../lib/pytis/data/types_.py:2587
msgid "One of hierarchical value items is too long"
msgstr "Jedna z položek hierarchické hodnoty je příliš dlouhá"

#: ../lib/pytis/data/types_.py:2589
msgid "One of hierarchical value items contains invalid characters"
msgstr "Jedna z položek hierarchické hodnoty obsahuje neplatné znaky"

#. User input validation error message.
#: ../lib/pytis/data/types_.py:2754
msgid "Not a JSON string"
msgstr ""

#: ../lib/pytis/data/types_.py:2756
msgid "Unsupported JSON value"
msgstr ""

#: ../lib/pytis/data/types_.py:2762
msgid "JSON value doesn't match schema definition"
msgstr ""

#: ../lib/pytis/presentation/field.py:482
msgid "Such value already exists."
msgstr "Taková hodnota již existuje"

#: ../lib/pytis/presentation/field.py:745
msgid "unlimited"
msgstr "neomezeno"

#~ msgid "Invalid date or time"
#~ msgstr "Chybné datum nebo čas"

#, python-format
#~ msgid "Not a buffer object: %r"
#~ msgstr "Není to objekt typu buffer: %r"

#~ msgid "Application error. You can report it to get it fixed soon."
#~ msgstr ""
#~ "Chyba aplikace. Můžete ji nyní nahlásit, aby mohla být co nejdříve "
#~ "opravena."

#~ msgid "Unable to connect to the database"
#~ msgstr "Nelze se připojit k databázi"

#~ msgid "Query arguments unsupported by the pgsql backend"
#~ msgstr "Argumenty dotazu nejsou podporovány při použití pgsql backendu"

#~ msgid "Characters present in data not representable in database encoding"
#~ msgstr "Data obsahují znaky, které nelze reprezentovat v kódování databáze"

#~ msgid "String exceeds max length %(maxlen)s characters"
#~ msgstr "Řetězec přesahuje maximální délku %(maxlen)s znaků"

#~ msgid "Minimal length %(minlen)s not satisfied"
#~ msgstr "Nedodržena minimální délka %(minlen)s"
