# Pytis translations 
# Copyright (C) 2008-2011 OUI Technology Ltd. 
# This file is distributed under the same license as the Pytis package. 
#
msgid ""
msgstr ""
"Project-Id-Version: 0.1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2025-04-15 18:44+0200\n"
"PO-Revision-Date: 2011-12-29 14:56+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: Hungarian <wiking@lists.freebsoft.org>\n"
"Language: hu\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ../lib/pytis/data/access.py:433
msgid "Access denied"
msgstr ""

#: ../lib/pytis/data/dbapi.py:91
msgid "Waiting for server recovery"
msgstr ""

#: ../lib/pytis/data/dbapi.py:103
msgid "Can't connect to database"
msgstr ""

#: ../lib/pytis/data/dbapi.py:233
msgid "Database interface error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:252
msgid "Database connection timeout"
msgstr ""

#: ../lib/pytis/data/dbapi.py:254 ../lib/pytis/data/dbapi.py:389
msgid "Database connection error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:268
msgid "Database operational error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:276
msgid "Database internal error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:280
msgid "Database integrity violation"
msgstr ""

#: ../lib/pytis/data/dbdata.py:294
msgid "Too many database connections"
msgstr ""

#: ../lib/pytis/data/dbdata.py:723
msgid "Database error"
msgstr ""

#: ../lib/pytis/data/dbdata.py:791
msgid "Invalid user name or password"
msgstr ""

#: ../lib/pytis/data/postgresql.py:443 ../lib/pytis/data/postgresql.py:553
#: ../lib/pytis/data/postgresql.py:565
msgid "Method not implemented"
msgstr ""

#: ../lib/pytis/data/postgresql.py:3583
msgid "Invalid database counter value"
msgstr ""

#: ../lib/pytis/data/types_.py:374
#, python-format
msgid "Wildcard matching not supported for values of type '%s'."
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:381
msgid "Empty value"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:397
msgid "Invalid value"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:545
#, python-format
msgid "Minimal value is %(minimum)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:548
#, python-format
msgid "Maximal value is %(maximum)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:588
#, python-format
msgid "Minimal size %(minlen)s not satisfied"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:590
#, python-format
msgid "Maximal size %(maxlen)s exceeded"
msgstr ""

#: ../lib/pytis/data/types_.py:741
msgid "Lower range bound higher than the upper one"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:834
msgid "Not an integer"
msgstr ""

#: ../lib/pytis/data/types_.py:1006
msgid "Invalid number"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1142
#, python-format
msgid "Minimal length %(minlen)s characters not satisfied"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1144
#, python-format
msgid "Maximal length %(maxlen)s characters exceeded"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1285
msgid "Please use mix of letters and non-letters in your password"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1291
msgid "Enter the password twice to eliminate typos"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1294
msgid "Passwords don't match"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1317
msgid "Invalid MD5 hash"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1324 ../lib/pytis/data/types_.py:1362
#: ../lib/pytis/data/types_.py:1392 ../lib/pytis/data/types_.py:1412
#: ../lib/pytis/data/types_.py:2142
msgid "Invalid format"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1347
msgid "Invalid color format ('#RGB' or '#RRGGBB')"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1367
#, python-format
msgid "Invalid inet address mask: %(mask)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1374
#, python-format
msgid "Invalid inet address value %(addr)s"
msgstr ""

#: ../lib/pytis/data/types_.py:1541
msgid "Invalid date or time format"
msgstr ""

#: ../lib/pytis/data/types_.py:1754
msgid "Date outside the allowed range"
msgstr ""

#: ../lib/pytis/data/types_.py:2158
#, python-format
msgid "%d min"
msgid_plural "%d min"
msgstr[0] ""

#: ../lib/pytis/data/types_.py:2160
#, python-format
msgid "%d h"
msgid_plural "%d h"
msgstr[0] ""

#: ../lib/pytis/data/types_.py:2162
#, python-format
msgid "%d day"
msgid_plural "%d days"
msgstr[0] ""

#: ../lib/pytis/data/types_.py:2164
msgid "less than 1 min"
msgstr ""

#: ../lib/pytis/data/types_.py:2275
msgid "Invalid boolean type input value"
msgstr ""

#: ../lib/pytis/data/types_.py:2502
msgid "Invalid graphics format"
msgstr ""

#: ../lib/pytis/data/types_.py:2560
#, python-format
msgid "Minimal pixel size %(minsize)s exceeded"
msgstr ""

#: ../lib/pytis/data/types_.py:2563
#, python-format
msgid "Maximal pixel size %(maxsize)s exceeded"
msgstr ""

#: ../lib/pytis/data/types_.py:2567
#, python-format
msgid "Unsupported format %(format)s; valid formats: %(formats)s"
msgstr ""

#: ../lib/pytis/data/types_.py:2614
msgid "Invalid hierarchical value format"
msgstr ""

#: ../lib/pytis/data/types_.py:2616
msgid "One of hierarchical value items is too long"
msgstr ""

#: ../lib/pytis/data/types_.py:2618
msgid "One of hierarchical value items contains invalid characters"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:2799
msgid "Not a JSON string"
msgstr ""

#: ../lib/pytis/data/types_.py:2803
msgid "Unsupported JSON value"
msgstr ""

#: ../lib/pytis/data/types_.py:2809
msgid "JSON value doesn't match schema definition"
msgstr ""

#: ../lib/pytis/presentation/field.py:484
msgid "Such value already exists."
msgstr ""

#: ../lib/pytis/presentation/field.py:759
msgid "unlimited"
msgstr ""

#: ../lib/pytis/presentation/spec.py:5802
#, python-format
msgid ""
"You don't have priviledges to invoke the action '%s'.\n"
"Please contact the access rights administrator."
msgstr ""

#, fuzzy
#~ msgid "Instructions"
#~ msgstr "Műveletek"

#, fuzzy
#~ msgid "Selections"
#~ msgstr "Műveletek"

#, fuzzy
#~ msgid "Dictation"
#~ msgstr "Műveletek"
